name: Question
description: Ask a question about usage or behavior
title: "[Question] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: |
        Ask your question here.
    validations:
      required: true
